#ifndef F030F4P6_BOARD_CONFIG_H_
#define F030F4P6_BOARD_CONFIG_H_

#include "stm32f0xx_hal.h"

#define SHIFT_REGISTER_DATA_GPIO GPIOA
#define SHIFT_REGISTER_DATA_PIN GPIO_PIN_2
#define SHIFT_REGISTER_LATCH_GPIO GPIOA
#define SHIFT_REGISTER_LATCH_PIN GPIO_PIN_3
#define SHIFT_REGISTER_CLOCK_GPIO GPIOA
#define SHIFT_REGISTER_CLOCK_PIN GPIO_PIN_5
#define SHIFT_REGISTER_OUTPUT_ENABLE_GPIO GPIOA
#define SHIFT_REGISTER_OUTPUT_ENABLE_PIN GPIO_PIN_6

#define SHIFT_REGISTER_OUTPUT_ENABLE_TIMER TIM3
#define SHIFT_REGISTER_OUTPUT_ENABLE_CHANNEL TIM_CHANNEL_1

#define BUTTONS_ADC_CHANNEL ADC_CHANNEL_1
#define LIGHT_SENSOR_ADC_CHANNEL ADC_CHANNEL_0

#define BUTTON_MODE_ADC_MAX 470U
#define BUTTON_SET_ADC_MAX 950U
#define BUTTON_UP_ADC_MAX 1630U
#define BUTTON_DOWN_ADC_MAX 2330U
#define BUTTON_OFF_ADC_MAX 3360U

#define LIGHT_SENSOR_ADC_DARK 1000U
#define LIGHT_SENSOR_ADC_BRIGHT 3200U
#define LIGHT_SENSOR_BRIGHTNESS_MIN 5U
#define LIGHT_SENSOR_BRIGHTNESS_MAX 70U
#define LIGHT_SENSOR_BRIGHTNESS_LEVELS 6U
#define LIGHT_SENSOR_ADC_HYSTERESIS 80U

#define DS1302_CLK_GPIO GPIOA
#define DS1302_CLK_PIN GPIO_PIN_7
#define DS1302_DATA_GPIO GPIOA
#define DS1302_DATA_PIN GPIO_PIN_9
#define DS1302_RST_GPIO GPIOA
#define DS1302_RST_PIN GPIO_PIN_10

#define DHT11_DATA_GPIO GPIOF
#define DHT11_DATA_PIN GPIO_PIN_1

#define BUZZER_GPIO GPIOB
#define BUZZER_PIN GPIO_PIN_1

#define SHIFT_REGISTER_Q0_BIT 0U
#define SHIFT_REGISTER_Q1_BIT 1U
#define SHIFT_REGISTER_Q2_BIT 2U
#define SHIFT_REGISTER_Q3_BIT 3U
#define SHIFT_REGISTER_Q4_BIT 4U
#define SHIFT_REGISTER_Q5_BIT 5U
#define SHIFT_REGISTER_Q6_BIT 6U
#define SHIFT_REGISTER_Q7_BIT 7U

#endif /* F030F4P6_BOARD_CONFIG_H_ */
