#ifndef BOARD_CONFIG_H_
#define BOARD_CONFIG_H_

#include "stm32f407_lowlevel.h"

#define SHIFT_REGISTER_GPIO GPIOA
#define SHIFT_REGISTER_DATA_PIN PIN_2
#define SHIFT_REGISTER_CLOCK_PIN PIN_4
#define SHIFT_REGISTER_LATCH_PIN PIN_3
#define SHIFT_REGISTER_OUTPUT_ENABLE_PIN PIN_6

#define SHIFT_REGISTER_Q0_BIT 0U
#define SHIFT_REGISTER_Q1_BIT 1U
#define SHIFT_REGISTER_Q2_BIT 2U
#define SHIFT_REGISTER_Q3_BIT 3U
#define SHIFT_REGISTER_Q4_BIT 4U
#define SHIFT_REGISTER_Q5_BIT 5U
#define SHIFT_REGISTER_Q6_BIT 6U
#define SHIFT_REGISTER_Q7_BIT 7U

#define BUTTONS_GPIO GPIOA
#define BUTTONS_PIN PIN_1
#define BUTTONS_ADC_CHANNEL 1U

#define LIGHT_SENSOR_GPIO GPIOA
#define LIGHT_SENSOR_PIN PIN_0
#define LIGHT_SENSOR_ADC_CHANNEL 0U

#define BUTTON_MODE_ADC_MAX 520U
#define BUTTON_SET_ADC_MAX 990U
#define BUTTON_UP_ADC_MAX 1670U
#define BUTTON_DOWN_ADC_MAX 2380U
#define BUTTON_OFF_ADC_MAX 3410U

#define LIGHT_SENSOR_ADC_DARK 1000U
#define LIGHT_SENSOR_ADC_BRIGHT 3200U
#define LIGHT_SENSOR_BRIGHTNESS_MIN 5U
#define LIGHT_SENSOR_BRIGHTNESS_MAX 70U
#define LIGHT_SENSOR_BRIGHTNESS_LEVELS 6U
#define LIGHT_SENSOR_ADC_HYSTERESIS 80U

#define DS1302_GPIO GPIOA
#define DS1302_CLK_PIN PIN_5
#define DS1302_DATA_PIN PIN_7
#define DS1302_RST_PIN PIN_8

#define DHT11_GPIO GPIOA
#define DHT11_DATA_PIN PIN_10

#define BUZZER_GPIO GPIOA
#define BUZZER_PIN PIN_15

#define BOARD_LOOP_DELAY_CYCLES 20000U

#endif /* BOARD_CONFIG_H_ */
