#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#define UI_TICKS_PER_SECOND 50U
#define AUTO_TIME_TICKS (15U * UI_TICKS_PER_SECOND)
#define AUTO_DATE_TICKS (5U * UI_TICKS_PER_SECOND)
#define AUTO_ENVIRONMENT_TICKS (5U * UI_TICKS_PER_SECOND)
#define AUTO_USER_PAUSE_TICKS (30U * UI_TICKS_PER_SECOND)
#define ENVIRONMENT_STARTUP_DELAY_TICKS (2U * UI_TICKS_PER_SECOND)
#define ENVIRONMENT_READ_TICKS (2U * UI_TICKS_PER_SECOND)
#define ENVIRONMENT_TEMPERATURE_DISPLAY_MAX 60U
#define ENVIRONMENT_HUMIDITY_DISPLAY_MAX 90U
#define ENVIRONMENT_HUMIDITY_DISPLAY_MIN 30U
#define ENVIRONMENT_HUMIDITY_LED_COUNT 6U
#define ENVIRONMENT_HUMIDITY_STEP 10U
#define ALARM_SLOT_COUNT 3U
#define ALARM_BUZZER_DURATION_TICKS (60U * UI_TICKS_PER_SECOND)
#define ALARM_BUZZER_BEEP_COUNT 3U
#define ALARM_BUZZER_BEEP_ON_TICKS 5U
#define ALARM_BUZZER_BEEP_SPACE_TICKS 7U
#define ALARM_BUZZER_GROUP_PAUSE_TICKS 45U
#define ALARM_BUZZER_BEEP_STEP_TICKS \
    (ALARM_BUZZER_BEEP_ON_TICKS + ALARM_BUZZER_BEEP_SPACE_TICKS)
#define ALARM_BUZZER_GROUP_TICKS \
    ((ALARM_BUZZER_BEEP_COUNT * ALARM_BUZZER_BEEP_STEP_TICKS) + \
     ALARM_BUZZER_GROUP_PAUSE_TICKS)
#define ALARM_EMPTY_SLOT_ERROR_TICKS UI_TICKS_PER_SECOND
#define OFF_LONG_PRESS_MS 2000U

#endif /* APP_CONFIG_H_ */
