/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
 /*MAP of PINS

PA1-> buttons with differend resistors(adc)
3.3V
 |
[10k]
 |
 +-------> PA1 / ADC_BUTTONS
 |
 +--[ MODE]--[1k]--GND
 |
 +--[ SET ]--[2k]--GND
 |
 +--[ UP  ]--[4.7k]--GND
 |
 +--[ DOWN]--[10k]--GND
 |
 +--[ OFF ]--[20k]--GND

PA0-> light sensor(adc)
3.3V
 |
[LDR]
 |
 +-------> PA0 / ADC_LIGHT
 |
[10k]
 |
GND

74HC595N wiring:
PA2 -> SER / DS / pin 14
PA4 -> SRCLK / SH_CP / pin 11
PA3 -> RCLK / ST_CP / pin 12
PA6 -> OE / pin 13
3.3V -> MR / SRCLR / pin 10
3.3V -> VCC / pin 16
GND -> GND / pin 8

DS1302Z wiring:
PA5 -> CLK
PA7 -> DATA / I/O
PA8 -> RST / CE
3.3V -> VCC
GND -> GND

HW-481 / DHT11 wiring:
PA10 -> DATA / S
5V -> VCC / +
GND -> GND / -

Active buzzer wiring:
PA15 -> NPN base through 1k..4.7k
3.3V -> 270R -> buzzer +
buzzer - -> NPN collector
NPN emitter -> GND

Second 74HC595N is chained from first register QH' to second register DS.

Board 1 outputs:
QA -> hours 32
QB -> hours 16
QC -> hours 8
QD -> hours 4
QE -> hours 2
QF -> hours 1
QG -> minutes 32
QH -> minutes 16

Board 2 outputs:
QA -> minutes 8
QB -> minutes 4
QC -> minutes 2
QD -> minutes 1
QE -> mode hours
QF -> mode date
QG -> mode environment
QH -> alarm set
Brightness:
PA0 light sensor controls brightness from 5% to 70%.
All Q0-Q7 outputs are enabled with the same brightness through OE dimming.
 */

#include <stdint.h>
#include "board.h"

typedef enum {
    DISPLAY_TIME = 0,
    DISPLAY_DATE,
    DISPLAY_ENVIRONMENT,
    DISPLAY_ALARM
} DisplayMode_t;

typedef enum {
    EDIT_NONE = 0,
    EDIT_MINUTES,
    EDIT_HOURS,
    EDIT_DAY,
    EDIT_MONTH,
    EDIT_ALARM_HOURS,
    EDIT_ALARM_MINUTES
} EditTarget_t;

typedef struct {
    uint8_t configured;
    uint8_t enabled;
    uint8_t hour;
    uint8_t minute;
} AlarmSlot_t;

#define UI_TICKS_PER_SECOND 50U
#define AUTO_TIME_TICKS (15U * UI_TICKS_PER_SECOND)
#define AUTO_DATE_TICKS (5U * UI_TICKS_PER_SECOND)
#define AUTO_ENVIRONMENT_TICKS (5U * UI_TICKS_PER_SECOND)
#define AUTO_USER_PAUSE_TICKS (30U * UI_TICKS_PER_SECOND)
#define ENVIRONMENT_READ_TICKS (2U * UI_TICKS_PER_SECOND)
#define ENVIRONMENT_TEMPERATURE_DISPLAY_MAX 60U
#define ENVIRONMENT_HUMIDITY_DISPLAY_MAX 90U
#define ENVIRONMENT_HUMIDITY_DISPLAY_MIN 30U
#define ENVIRONMENT_HUMIDITY_LED_COUNT 6U
#define ENVIRONMENT_HUMIDITY_STEP 10U
#define ALARM_SLOT_COUNT 3U
#define ALARM_RAM_SIGNATURE 0xA7U
#define ALARM_RAM_VERSION 0x01U
#define ALARM_RAM_CHECKSUM_XOR 0x5AU
#define ALARM_BUZZER_DURATION_TICKS (60U * UI_TICKS_PER_SECOND)
#define ALARM_BUZZER_BEEP_COUNT 3U
#define ALARM_BUZZER_BEEP_ON_TICKS 5U
#define ALARM_BUZZER_BEEP_SPACE_TICKS 7U
#define ALARM_BUZZER_GROUP_PAUSE_TICKS 45U
#define ALARM_BUZZER_BEEP_STEP_TICKS \
    (ALARM_BUZZER_BEEP_ON_TICKS + ALARM_BUZZER_BEEP_SPACE_TICKS)
#define ALARM_BUZZER_GROUP_TICKS \
    ((ALARM_BUZZER_BEEP_COUNT * ALARM_BUZZER_BEEP_STEP_TICKS) + \
     ALARM_BUZZER_GROUP_PAUSE_TICKS)
#define OFF_LONG_PRESS_TICKS (2U * UI_TICKS_PER_SECOND)

static DisplayMode_t displayMode = DISPLAY_TIME;
static EditTarget_t editTarget = EDIT_NONE;
static ClockDateTime_t currentDateTime = {0U, 0U, 12U, 1U, 1U};
static ClockEnvironment_t currentEnvironment = {0U, 0U, 0U};
static AlarmSlot_t alarmSlots[ALARM_SLOT_COUNT] = {{0U, 0U, 0U, 0U},
                                                   {0U, 0U, 0U, 0U},
                                                   {0U, 0U, 0U, 0U}};
static uint8_t selectedAlarmSlot = 0U;
static uint32_t alarmBuzzerTicks = 0U;
static uint8_t lastAlarmTriggerHour = 255U;
static uint8_t lastAlarmTriggerMinute = 255U;
static uint32_t autoModeTicks = 0U;
static uint32_t userPauseTicks = 0U;
static uint32_t environmentReadTicks = 0U;

static uint8_t MonthDays(uint8_t month) {
    switch (month) {
    case 4U:
    case 6U:
    case 9U:
    case 11U:
        return 30U;
    case 2U:
        return 28U;
    case 1U:
    case 3U:
    case 5U:
    case 7U:
    case 8U:
    case 10U:
    case 12U:
    default:
        return 31U;
    }
}

static uint8_t IncrementWrap(uint8_t value, uint8_t minimum, uint8_t maximum) {
    if (value >= maximum) {
        return minimum;
    }
    return (uint8_t)(value + 1U);
}

static uint8_t DecrementWrap(uint8_t value, uint8_t minimum, uint8_t maximum) {
    if (value <= minimum) {
        return maximum;
    }
    return (uint8_t)(value - 1U);
}

static void SaveTimeToRtc(void) {
    Board_WriteTime(currentDateTime.hours, currentDateTime.minutes,
                     currentDateTime.seconds);
}

static void SaveDateToRtc(void) {
    Board_WriteDate(currentDateTime.day, currentDateTime.month);
}

static uint8_t AlarmSlotFlags(const AlarmSlot_t *slot) {
    uint8_t flags = 0U;

    if (slot->configured != 0U) {
        flags |= 0x01U;
    }
    if (slot->enabled != 0U) {
        flags |= 0x02U;
    }

    return flags;
}

static uint8_t AlarmRamChecksum(const uint8_t *data, uint8_t size) {
    uint8_t checksum = 0U;

    for (uint8_t index = 0U; index < size; ++index) {
        checksum = (uint8_t)(checksum + data[index]);
    }

    return (uint8_t)(checksum ^ ALARM_RAM_CHECKSUM_XOR);
}

static uint8_t IsAlarmRamImageValid(const uint8_t *ramImage) {
    return ((ramImage[0U] == ALARM_RAM_SIGNATURE) &&
            (ramImage[1U] == ALARM_RAM_VERSION) &&
            (ramImage[11U] == AlarmRamChecksum(ramImage, 11U)));
}

static void SaveAlarmsToRtcRam(void) {
    uint8_t ramImage[12U] = {0U};

    ramImage[0U] = ALARM_RAM_SIGNATURE;
    ramImage[1U] = ALARM_RAM_VERSION;
    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        uint8_t offset = (uint8_t)(2U + (slotIndex * 3U));
        ramImage[offset] = AlarmSlotFlags(&alarmSlots[slotIndex]);
        ramImage[offset + 1U] = alarmSlots[slotIndex].hour;
        ramImage[offset + 2U] = alarmSlots[slotIndex].minute;
    }
    ramImage[11U] = AlarmRamChecksum(ramImage, 11U);

    Board_WriteAlarmStorage(ramImage, sizeof(ramImage));
}

static void ClearAlarms(void) {
    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        alarmSlots[slotIndex].configured = 0U;
        alarmSlots[slotIndex].enabled = 0U;
        alarmSlots[slotIndex].hour = 0U;
        alarmSlots[slotIndex].minute = 0U;
    }
}

static void LoadAlarmsFromRtcRam(void) {
    uint8_t ramImage[12U] = {0U};

    for (uint8_t attempt = 0U; attempt < 3U; ++attempt) {
        Board_ReadAlarmStorage(ramImage, sizeof(ramImage));
        if (IsAlarmRamImageValid(ramImage) != 0U) {
            break;
        }
    }

    if (IsAlarmRamImageValid(ramImage) == 0U) {
        ClearAlarms();
        return;
    }

    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        uint8_t offset = (uint8_t)(2U + (slotIndex * 3U));
        uint8_t flags = ramImage[offset];
        uint8_t hour = ramImage[offset + 1U];
        uint8_t minute = ramImage[offset + 2U];

        alarmSlots[slotIndex].configured = (uint8_t)(flags & 0x01U);
        alarmSlots[slotIndex].enabled = (uint8_t)((flags >> 1U) & 0x01U);
        alarmSlots[slotIndex].hour = (hour <= 23U) ? hour : 0U;
        alarmSlots[slotIndex].minute = (minute <= 59U) ? minute : 0U;
        if (alarmSlots[slotIndex].configured == 0U) {
            alarmSlots[slotIndex].enabled = 0U;
        }
    }
}

static uint8_t AnyAlarmEnabled(void) {
    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        if (alarmSlots[slotIndex].enabled != 0U) {
            return 1U;
        }
    }

    return 0U;
}

static void ReadEnvironmentSensor(void) {
    ClockEnvironment_t readEnvironment = currentEnvironment;

    if (Board_ReadEnvironment(&readEnvironment) != 0U) {
        currentEnvironment = readEnvironment;
    }

    environmentReadTicks = ENVIRONMENT_READ_TICKS;
}

static void StopAlarmBuzzer(void) {
    alarmBuzzerTicks = 0U;
    Board_SetBuzzer(0U);
}

static void DisableAllAlarms(void) {
    StopAlarmBuzzer();

    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        alarmSlots[slotIndex].enabled = 0U;
    }

    editTarget = EDIT_NONE;
    SaveAlarmsToRtcRam();
}

static void NormalizeDateTime(void) {
    if (currentDateTime.seconds > 59U) {
        currentDateTime.seconds = 0U;
    }
    if (currentDateTime.minutes > 59U) {
        currentDateTime.minutes = 0U;
    }
    if (currentDateTime.hours > 23U) {
        currentDateTime.hours = 12U;
    }
    if ((currentDateTime.month < 1U) || (currentDateTime.month > 12U)) {
        currentDateTime.month = 1U;
    }
    if ((currentDateTime.day < 1U) ||
        (currentDateTime.day > MonthDays(currentDateTime.month))) {
        currentDateTime.day = 1U;
    }
}

static void HandleModeButton(void) {
    StopAlarmBuzzer();
    editTarget = EDIT_NONE;
    Board_ReadDateTime(&currentDateTime);
    NormalizeDateTime();

    if (displayMode == DISPLAY_TIME) {
        displayMode = DISPLAY_DATE;
    } else if (displayMode == DISPLAY_DATE) {
        displayMode = DISPLAY_ENVIRONMENT;
    } else if (displayMode == DISPLAY_ENVIRONMENT) {
        displayMode = DISPLAY_ALARM;
    } else {
        displayMode = DISPLAY_TIME;
    }
}

static void HandleSetButton(void) {
    StopAlarmBuzzer();
    if (displayMode == DISPLAY_TIME) {
        if ((editTarget == EDIT_NONE) || (editTarget == EDIT_HOURS)) {
            editTarget = EDIT_MINUTES;
        } else {
            editTarget = EDIT_HOURS;
        }
    } else if (displayMode == DISPLAY_DATE) {
        if ((editTarget == EDIT_NONE) || (editTarget == EDIT_MONTH)) {
            editTarget = EDIT_DAY;
        } else {
            editTarget = EDIT_MONTH;
        }
    } else if (displayMode == DISPLAY_ALARM) {
        if ((editTarget == EDIT_NONE) || (editTarget == EDIT_ALARM_MINUTES)) {
            editTarget = EDIT_ALARM_HOURS;
        } else {
            editTarget = EDIT_ALARM_MINUTES;
        }
    }
}

static void HandleUpButton(void) {
    StopAlarmBuzzer();
    switch (editTarget) {
    case EDIT_MINUTES:
        currentDateTime.minutes = IncrementWrap(currentDateTime.minutes, 0U, 59U);
        currentDateTime.seconds = 0U;
        SaveTimeToRtc();
        break;
    case EDIT_HOURS:
        currentDateTime.hours = IncrementWrap(currentDateTime.hours, 0U, 23U);
        SaveTimeToRtc();
        break;
    case EDIT_DAY:
        currentDateTime.day =
            IncrementWrap(currentDateTime.day, 1U, MonthDays(currentDateTime.month));
        SaveDateToRtc();
        break;
    case EDIT_MONTH:
        currentDateTime.month = IncrementWrap(currentDateTime.month, 1U, 12U);
        if (currentDateTime.day > MonthDays(currentDateTime.month)) {
            currentDateTime.day = MonthDays(currentDateTime.month);
        }
        SaveDateToRtc();
        break;
    case EDIT_ALARM_HOURS:
        alarmSlots[selectedAlarmSlot].hour =
            IncrementWrap(alarmSlots[selectedAlarmSlot].hour, 0U, 23U);
        break;
    case EDIT_ALARM_MINUTES:
        alarmSlots[selectedAlarmSlot].minute =
            IncrementWrap(alarmSlots[selectedAlarmSlot].minute, 0U, 59U);
        break;
    case EDIT_NONE:
    default:
        if (displayMode == DISPLAY_ALARM) {
            selectedAlarmSlot =
                IncrementWrap(selectedAlarmSlot, 0U, (uint8_t)(ALARM_SLOT_COUNT - 1U));
        }
        break;
    }
}

static void HandleDownButton(void) {
    StopAlarmBuzzer();
    switch (editTarget) {
    case EDIT_MINUTES:
        currentDateTime.minutes = DecrementWrap(currentDateTime.minutes, 0U, 59U);
        currentDateTime.seconds = 0U;
        SaveTimeToRtc();
        break;
    case EDIT_HOURS:
        currentDateTime.hours = DecrementWrap(currentDateTime.hours, 0U, 23U);
        SaveTimeToRtc();
        break;
    case EDIT_DAY:
        currentDateTime.day =
            DecrementWrap(currentDateTime.day, 1U, MonthDays(currentDateTime.month));
        SaveDateToRtc();
        break;
    case EDIT_MONTH:
        currentDateTime.month = DecrementWrap(currentDateTime.month, 1U, 12U);
        if (currentDateTime.day > MonthDays(currentDateTime.month)) {
            currentDateTime.day = MonthDays(currentDateTime.month);
        }
        SaveDateToRtc();
        break;
    case EDIT_ALARM_HOURS:
        alarmSlots[selectedAlarmSlot].hour =
            DecrementWrap(alarmSlots[selectedAlarmSlot].hour, 0U, 23U);
        break;
    case EDIT_ALARM_MINUTES:
        alarmSlots[selectedAlarmSlot].minute =
            DecrementWrap(alarmSlots[selectedAlarmSlot].minute, 0U, 59U);
        break;
    case EDIT_NONE:
    default:
        if (displayMode == DISPLAY_ALARM) {
            selectedAlarmSlot =
                DecrementWrap(selectedAlarmSlot, 0U, (uint8_t)(ALARM_SLOT_COUNT - 1U));
        }
        break;
    }
}

static void HandleOffButton(void) {
    StopAlarmBuzzer();
    if (displayMode == DISPLAY_ALARM) {
        if (editTarget != EDIT_NONE) {
            alarmSlots[selectedAlarmSlot].configured = 1U;
            alarmSlots[selectedAlarmSlot].enabled = 1U;
            SaveAlarmsToRtcRam();
            editTarget = EDIT_NONE;
            return;
        }

        if (alarmSlots[selectedAlarmSlot].enabled != 0U) {
            alarmSlots[selectedAlarmSlot].enabled = 0U;
            SaveAlarmsToRtcRam();
            return;
        }
    }

    editTarget = EDIT_NONE;
    Board_ReadDateTime(&currentDateTime);
    NormalizeDateTime();
}

static void HandleButton(ClockButton_t button) {
    userPauseTicks = AUTO_USER_PAUSE_TICKS;

    switch (button) {
    case CLOCK_BUTTON_MODE:
        HandleModeButton();
        break;
    case CLOCK_BUTTON_SET:
        HandleSetButton();
        break;
    case CLOCK_BUTTON_UP:
        HandleUpButton();
        break;
    case CLOCK_BUTTON_DOWN:
        HandleDownButton();
        break;
    case CLOCK_BUTTON_OFF:
        HandleOffButton();
        break;
    case CLOCK_BUTTON_NONE:
    default:
        break;
    }
}

static uint32_t AutoModeDurationTicks(DisplayMode_t mode) {
    if (mode == DISPLAY_TIME) {
        return AUTO_TIME_TICKS;
    }
    if (mode == DISPLAY_DATE) {
        return AUTO_DATE_TICKS;
    }
    return AUTO_ENVIRONMENT_TICKS;
}

static void AdvanceAutoMode(void) {
    if (displayMode == DISPLAY_TIME) {
        displayMode = DISPLAY_DATE;
    } else if (displayMode == DISPLAY_DATE) {
        displayMode = DISPLAY_ENVIRONMENT;
    } else {
        displayMode = DISPLAY_TIME;
    }
    autoModeTicks = 0U;
}

static void UpdateAutoModeCycle(void) {
    if (userPauseTicks > 0U) {
        --userPauseTicks;
        if (userPauseTicks == 0U) {
            editTarget = EDIT_NONE;
            displayMode = DISPLAY_TIME;
            autoModeTicks = 0U;
            Board_ReadDateTime(&currentDateTime);
            NormalizeDateTime();
        }
        return;
    }

    if (editTarget != EDIT_NONE) {
        return;
    }

    if (displayMode == DISPLAY_ALARM) {
        return;
    }

    ++autoModeTicks;
    if (autoModeTicks >= AutoModeDurationTicks(displayMode)) {
        AdvanceAutoMode();
    }
}

static uint8_t HoursToBoard1Mask(uint8_t hours) {
    uint8_t mask = 0U;

    if ((hours & 32U) != 0U) {
        mask |= (uint8_t)(1U << CLOCK_BOARD1_HOURS_32_BIT);
    }
    if ((hours & 16U) != 0U) {
        mask |= (uint8_t)(1U << CLOCK_BOARD1_HOURS_16_BIT);
    }
    if ((hours & 8U) != 0U) {
        mask |= (uint8_t)(1U << CLOCK_BOARD1_HOURS_8_BIT);
    }
    if ((hours & 4U) != 0U) {
        mask |= (uint8_t)(1U << CLOCK_BOARD1_HOURS_4_BIT);
    }
    if ((hours & 2U) != 0U) {
        mask |= (uint8_t)(1U << CLOCK_BOARD1_HOURS_2_BIT);
    }
    if ((hours & 1U) != 0U) {
        mask |= (uint8_t)(1U << CLOCK_BOARD1_HOURS_1_BIT);
    }

    return mask;
}

static void AddMinutesToDisplay(uint8_t minutes, uint8_t *board1Mask,
                                uint8_t *board2Mask) {
    if ((minutes & 32U) != 0U) {
        *board1Mask |= (uint8_t)(1U << CLOCK_BOARD1_MINUTES_32_BIT);
    }
    if ((minutes & 16U) != 0U) {
        *board1Mask |= (uint8_t)(1U << CLOCK_BOARD1_MINUTES_16_BIT);
    }
    if ((minutes & 8U) != 0U) {
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_8_BIT);
    }
    if ((minutes & 4U) != 0U) {
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_4_BIT);
    }
    if ((minutes & 2U) != 0U) {
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_2_BIT);
    }
    if ((minutes & 1U) != 0U) {
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_1_BIT);
    }
}

static void AddHumidityScaleLed(uint8_t ledIndex, uint8_t *board1Mask,
                                uint8_t *board2Mask) {
    switch (ledIndex) {
    case 0U:
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_1_BIT);
        break;
    case 1U:
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_2_BIT);
        break;
    case 2U:
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_4_BIT);
        break;
    case 3U:
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_MINUTES_8_BIT);
        break;
    case 4U:
        *board1Mask |= (uint8_t)(1U << CLOCK_BOARD1_MINUTES_16_BIT);
        break;
    case 5U:
        *board1Mask |= (uint8_t)(1U << CLOCK_BOARD1_MINUTES_32_BIT);
        break;
    default:
        break;
    }
}

static void AddHumidityToEnvironmentDisplay(uint8_t humidity, uint8_t *board1Mask,
                                            uint8_t *board2Mask) {
    uint8_t fullLedCount = 0U;

    if (humidity >= ENVIRONMENT_HUMIDITY_DISPLAY_MAX) {
        fullLedCount = ENVIRONMENT_HUMIDITY_LED_COUNT;
    } else if (humidity > ENVIRONMENT_HUMIDITY_DISPLAY_MIN) {
        uint8_t humidityOffset =
            (uint8_t)(humidity - ENVIRONMENT_HUMIDITY_DISPLAY_MIN);
        fullLedCount = (uint8_t)(humidityOffset / ENVIRONMENT_HUMIDITY_STEP);
    }

    for (uint8_t ledIndex = 0U; ledIndex < fullLedCount; ++ledIndex) {
        AddHumidityScaleLed(ledIndex, board1Mask, board2Mask);
    }
}

static uint8_t ModeToBoard2Mask(void) {
    if (displayMode == DISPLAY_TIME) {
        return (uint8_t)(1U << CLOCK_BOARD2_MODE_TIME_BIT);
    }
    if (displayMode == DISPLAY_DATE) {
        return (uint8_t)(1U << CLOCK_BOARD2_MODE_DATE_BIT);
    }
    if (displayMode == DISPLAY_ENVIRONMENT) {
        return (uint8_t)(1U << CLOCK_BOARD2_MODE_ENVIRONMENT_BIT);
    }
    return 0U;
}

static uint8_t AlarmSlotLedBit(uint8_t slotIndex) {
    switch (slotIndex) {
    case 0U:
        return CLOCK_BOARD2_MODE_TIME_BIT;
    case 1U:
        return CLOCK_BOARD2_MODE_DATE_BIT;
    case 2U:
    default:
        return CLOCK_BOARD2_MODE_ENVIRONMENT_BIT;
    }
}

static void AddAlarmStatusToDisplay(uint8_t *board2Mask) {
    if ((displayMode == DISPLAY_ALARM) || (AnyAlarmEnabled() != 0U)) {
        *board2Mask |= (uint8_t)(1U << CLOCK_BOARD2_ALARM_BIT);
    }
}

static void AddAlarmSlotsToDisplay(uint8_t blinkOn, uint8_t *board2Mask) {
    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        uint8_t bitMask = (uint8_t)(1U << AlarmSlotLedBit(slotIndex));
        uint8_t isSelected = (slotIndex == selectedAlarmSlot);
        uint8_t isEnabled = alarmSlots[slotIndex].enabled;
        uint8_t isConfigured = alarmSlots[slotIndex].configured;

        if (isEnabled != 0U) {
            if ((isSelected == 0U) || (blinkOn != 0U)) {
                *board2Mask |= bitMask;
            }
        } else if ((isConfigured != 0U) && (isSelected != 0U) && (blinkOn != 0U)) {
            *board2Mask |= bitMask;
        } else if ((isConfigured == 0U) && (isSelected != 0U) && (blinkOn != 0U)) {
            *board2Mask |= bitMask;
        }
    }
}

static void BuildTimeDisplay(uint8_t *board1Mask, uint8_t *board2Mask) {
    *board1Mask = HoursToBoard1Mask(currentDateTime.hours);
    *board2Mask = ModeToBoard2Mask();
    AddMinutesToDisplay(currentDateTime.minutes, board1Mask, board2Mask);
}

static void BuildDateDisplay(uint8_t *board1Mask, uint8_t *board2Mask) {
    *board1Mask = HoursToBoard1Mask(currentDateTime.month);
    *board2Mask = ModeToBoard2Mask();
    AddMinutesToDisplay(currentDateTime.day, board1Mask, board2Mask);
}

static void BuildEnvironmentDisplay(uint8_t *board1Mask, uint8_t *board2Mask) {
    uint8_t displayTemperature = currentEnvironment.temperature;
    uint8_t displayHumidity = currentEnvironment.humidity;

    *board1Mask = 0U;
    *board2Mask = ModeToBoard2Mask();

    if (displayTemperature > ENVIRONMENT_TEMPERATURE_DISPLAY_MAX) {
        displayTemperature = ENVIRONMENT_TEMPERATURE_DISPLAY_MAX;
    }
    if (displayHumidity > ENVIRONMENT_HUMIDITY_DISPLAY_MAX) {
        displayHumidity = ENVIRONMENT_HUMIDITY_DISPLAY_MAX;
    }

    *board1Mask = HoursToBoard1Mask(displayTemperature);
    AddHumidityToEnvironmentDisplay(displayHumidity, board1Mask, board2Mask);
}

static void BuildAlarmDisplay(uint8_t blinkOn, uint8_t *board1Mask,
                              uint8_t *board2Mask) {
    AlarmSlot_t *slot = &alarmSlots[selectedAlarmSlot];

    *board1Mask = 0U;
    *board2Mask = 0U;
    AddAlarmStatusToDisplay(board2Mask);
    AddAlarmSlotsToDisplay(blinkOn, board2Mask);

    if (editTarget == EDIT_ALARM_HOURS) {
        if (blinkOn != 0U) {
            *board1Mask = HoursToBoard1Mask(slot->hour);
        }
        AddMinutesToDisplay(slot->minute, board1Mask, board2Mask);
        return;
    }

    if (editTarget == EDIT_ALARM_MINUTES) {
        *board1Mask = HoursToBoard1Mask(slot->hour);
        if (blinkOn != 0U) {
            AddMinutesToDisplay(slot->minute, board1Mask, board2Mask);
        }
        return;
    }

    *board1Mask = HoursToBoard1Mask(slot->hour);
    AddMinutesToDisplay(slot->minute, board1Mask, board2Mask);
}

static void UpdateEnvironment(void) {
    if (environmentReadTicks > 0U) {
        --environmentReadTicks;
        return;
    }

    ReadEnvironmentSensor();
}

static void BuildDisplay(uint8_t blinkOn, uint8_t *board1Mask, uint8_t *board2Mask) {
    if (displayMode == DISPLAY_ALARM) {
        BuildAlarmDisplay(blinkOn, board1Mask, board2Mask);
        return;
    }

    if (editTarget != EDIT_NONE) {
        *board1Mask = 0U;
        *board2Mask = ModeToBoard2Mask();
        AddAlarmStatusToDisplay(board2Mask);

        if (blinkOn == 0U) {
            return;
        }

        switch (editTarget) {
        case EDIT_MINUTES:
            AddMinutesToDisplay(currentDateTime.minutes, board1Mask, board2Mask);
            break;
        case EDIT_HOURS:
            *board1Mask = HoursToBoard1Mask(currentDateTime.hours);
            break;
        case EDIT_DAY:
            AddMinutesToDisplay(currentDateTime.day, board1Mask, board2Mask);
            break;
        case EDIT_MONTH:
            *board1Mask = HoursToBoard1Mask(currentDateTime.month);
            break;
        case EDIT_NONE:
        default:
            break;
        }
        return;
    }

    if (displayMode == DISPLAY_TIME) {
        BuildTimeDisplay(board1Mask, board2Mask);
        AddAlarmStatusToDisplay(board2Mask);
        return;
    }
    if (displayMode == DISPLAY_DATE) {
        BuildDateDisplay(board1Mask, board2Mask);
        AddAlarmStatusToDisplay(board2Mask);
        return;
    }

    BuildEnvironmentDisplay(board1Mask, board2Mask);
    AddAlarmStatusToDisplay(board2Mask);
}

static void UpdateAlarmTrigger(void) {
    if ((currentDateTime.hours == lastAlarmTriggerHour) &&
        (currentDateTime.minutes == lastAlarmTriggerMinute)) {
        return;
    }

    for (uint8_t slotIndex = 0U; slotIndex < ALARM_SLOT_COUNT; ++slotIndex) {
        AlarmSlot_t *slot = &alarmSlots[slotIndex];

        if ((slot->enabled != 0U) && (slot->configured != 0U) &&
            (slot->hour == currentDateTime.hours) &&
            (slot->minute == currentDateTime.minutes)) {
            alarmBuzzerTicks = ALARM_BUZZER_DURATION_TICKS;
            lastAlarmTriggerHour = currentDateTime.hours;
            lastAlarmTriggerMinute = currentDateTime.minutes;
            return;
        }
    }
}

static void UpdateBuzzer(void) {
    uint8_t buzzerOn = 0U;

    if (alarmBuzzerTicks > 0U) {
        uint32_t elapsedTicks = ALARM_BUZZER_DURATION_TICKS - alarmBuzzerTicks;
        uint32_t groupPhase = elapsedTicks % ALARM_BUZZER_GROUP_TICKS;
        uint32_t beepsWindowTicks =
            ALARM_BUZZER_BEEP_COUNT * ALARM_BUZZER_BEEP_STEP_TICKS;

        if (groupPhase < beepsWindowTicks) {
            uint32_t beepPhase = groupPhase % ALARM_BUZZER_BEEP_STEP_TICKS;
            buzzerOn = (beepPhase < ALARM_BUZZER_BEEP_ON_TICKS) ? 1U : 0U;
        }
        --alarmBuzzerTicks;
    }

    Board_SetBuzzer(buzzerOn);
}

int main(void)
{
    Board_Init();
    Board_ReadDateTime(&currentDateTime);
    NormalizeDateTime();
    LoadAlarmsFromRtcRam();
    ReadEnvironmentSensor();

    ClockButton_t lastButton = CLOCK_BUTTON_NONE;
    uint32_t offButtonHoldTicks = 0U;
    uint8_t offLongPressHandled = 0U;
    uint32_t loopCounter = 0U;
    Board_WriteDisplay((ClockDisplay_t){0x00U, 0x00U});

    /* Loop forever */
    for (;;) {
        ClockButton_t pressedButton = Board_ReadButton();
        if (pressedButton == CLOCK_BUTTON_OFF) {
            if (offButtonHoldTicks < OFF_LONG_PRESS_TICKS) {
                ++offButtonHoldTicks;
            }
            if ((offButtonHoldTicks >= OFF_LONG_PRESS_TICKS) &&
                (offLongPressHandled == 0U)) {
                userPauseTicks = AUTO_USER_PAUSE_TICKS;
                DisableAllAlarms();
                offLongPressHandled = 1U;
            }
        } else {
            if ((lastButton == CLOCK_BUTTON_OFF) && (offLongPressHandled == 0U)) {
                HandleButton(CLOCK_BUTTON_OFF);
            }
            offButtonHoldTicks = 0U;
            offLongPressHandled = 0U;
        }

        if ((pressedButton != CLOCK_BUTTON_NONE) && (pressedButton != CLOCK_BUTTON_OFF) &&
            (pressedButton != lastButton)) {
            HandleButton(pressedButton);
        }
        lastButton = pressedButton;
        UpdateAutoModeCycle();
        UpdateEnvironment();

        uint8_t brightness = Board_ReadBrightness();
        uint8_t blinkOn = ((loopCounter / 80U) % 2U) == 0U;
        uint8_t board1Mask = 0U;
        uint8_t board2Mask = 0U;

        if ((editTarget == EDIT_NONE) && ((loopCounter % 200U) == 0U)) {
            Board_ReadDateTime(&currentDateTime);
            NormalizeDateTime();
            UpdateAlarmTrigger();
        }
        UpdateBuzzer();

        Board_SetBrightness(brightness);
        BuildDisplay(blinkOn, &board1Mask, &board2Mask);
        Board_WriteDisplay((ClockDisplay_t){board1Mask, board2Mask});

        ++loopCounter;
        Board_DelayLoop();
    }
}
