/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#include "alarm_manager.h"
#include "board.h"
#include "display_renderer.h"
#include "environment_manager.h"
#include "ui_controller.h"

int main(void)
{
    Board_Init();
    UiController_Init();
    AlarmManager_Init();
    EnvironmentManager_Init();

    uint32_t loopCounter = 0U;
    Board_WriteDisplay((ClockDisplay_t){0x00U, 0x00U});

    /* Loop forever */
    for (;;) {
        UiController_UpdateButton(Board_ReadButton());
        UiController_UpdateAutoModeCycle();
        EnvironmentManager_Update();

        uint8_t brightness = Board_ReadBrightness();
        uint8_t blinkOn = ((loopCounter / 80U) % 2U) == 0U;

        if ((UiController_EditTarget() == EDIT_NONE) &&
            ((loopCounter % 200U) == 0U)) {
            UiController_RefreshDateTime();
            AlarmManager_UpdateTrigger(UiController_DateTime());
        }
        AlarmManager_UpdateBuzzer();

        Board_SetBrightness(brightness);
        Board_WriteDisplay(DisplayRenderer_Build(
            UiController_DisplayMode(), UiController_EditTarget(),
            UiController_DateTime(), EnvironmentManager_Current(),
            AlarmManager_Slots(), AlarmManager_SlotCount(),
            AlarmManager_SelectedSlot(), AlarmManager_AnyEnabled(), blinkOn));

        ++loopCounter;
        Board_DelayLoop();
    }
}
