#ifndef L010F4P6_BOARD_CONFIG_H_
#define L010F4P6_BOARD_CONFIG_H_

#include "stm32l0xx_hal.h"

#define SHIFT_REGISTER_DATA_GPIO GPIOA
#define SHIFT_REGISTER_DATA_PIN GPIO_PIN_2
#define SHIFT_REGISTER_LATCH_GPIO GPIOA
#define SHIFT_REGISTER_LATCH_PIN GPIO_PIN_3
#define SHIFT_REGISTER_CLOCK_GPIO GPIOA
#define SHIFT_REGISTER_CLOCK_PIN GPIO_PIN_4
#define SHIFT_REGISTER_OUTPUT_ENABLE_GPIO GPIOA
#define SHIFT_REGISTER_OUTPUT_ENABLE_PIN GPIO_PIN_5

#define BOARD_I2C_SCL_GPIO GPIOA
#define BOARD_I2C_SCL_PIN GPIO_PIN_9
#define BOARD_I2C_SDA_GPIO GPIOA
#define BOARD_I2C_SDA_PIN GPIO_PIN_10

#define BUZZER_GPIO GPIOA
#define BUZZER_PIN GPIO_PIN_6

#define MAIN_POWER_SENSE_ADC_CHANNEL ADC_CHANNEL_9
#define MAIN_POWER_SENSE_ADC_CAL_MV 2140U
#define MAIN_POWER_SENSE_BATTERY_CAL_MV 3650U
#define MAIN_POWER_BATTERY_MV_MIN 2900U
#define MAIN_POWER_BATTERY_MV_MAX 4200U
#define MAIN_POWER_WAKEUP_GPIO GPIOA
#define MAIN_POWER_WAKEUP_GPIO_PIN GPIO_PIN_0
#define MAIN_POWER_WAKEUP_PIN PWR_WAKEUP_PIN1

#define BUTTONS_ADC_CHANNEL ADC_CHANNEL_1

#define BUTTON_MODE_ADC_MAX 470U
#define BUTTON_SET_ADC_MAX 950U
#define BUTTON_UP_ADC_MAX 1630U
#define BUTTON_DOWN_ADC_MAX 2330U
#define BUTTON_OFF_ADC_MAX 3360U

#define LIGHT_SENSOR_BRIGHTNESS_MIN 2U
#define LIGHT_SENSOR_BRIGHTNESS_MAX 50U
#define LIGHT_SENSOR_BRIGHTNESS_LEVELS 10U
#define LIGHT_SENSOR_LUX_DARK 2U
#define LIGHT_SENSOR_LUX_BRIGHT 400U
#define LIGHT_SENSOR_LUX_HYSTERESIS 5U

#endif /* L010F4P6_BOARD_CONFIG_H_ */
